// Generated by rive-viewmodel-generator from data_bind_runtime_test.riv.
// Do not edit this file manually.
import { RiveBindViewModelInstanceParams, UntypedRiveViewModel } from '@betclicgroup/common/cdk/assets/rive';

export const DataBindRuntimeTestViewModelName = {
    VM1: 'vm1',
    VM2: 'vm2',
    VM3: 'vm3',
} as const;

export interface Vm1ViewModel {
    readonly vm2: Vm2ViewModel;
    setOuter(value: string): void;
}

export interface Vm2ViewModel {
    readonly vm3: Vm3ViewModel;
}

export interface Vm3ViewModel {
    setInner(value: string): void;
}

export function createVm1ViewModel(viewModel: UntypedRiveViewModel, path?: string): Vm1ViewModel {
    return {
        get vm2(): Vm2ViewModel {
            return createVm2ViewModel(viewModel, path ? `${path}/vm2` : 'vm2');
        },
        setOuter: value => viewModel.setString('outer', value, path),
    };
}

export function createVm2ViewModel(viewModel: UntypedRiveViewModel, path?: string): Vm2ViewModel {
    return {
        get vm3(): Vm3ViewModel {
            return createVm3ViewModel(viewModel, path ? `${path}/vm3` : 'vm3');
        },
    };
}

export function createVm3ViewModel(viewModel: UntypedRiveViewModel, path?: string): Vm3ViewModel {
    return {
        setInner: value => viewModel.setString('inner', value, path),
    };
}

export function createVm1Binding(): RiveBindViewModelInstanceParams {
    return {
        viewModelName: DataBindRuntimeTestViewModelName.VM1,
    };
}

export function createVm2Binding(): RiveBindViewModelInstanceParams {
    return {
        viewModelName: DataBindRuntimeTestViewModelName.VM2,
    };
}

export function createVm3Binding(): RiveBindViewModelInstanceParams {
    return {
        viewModelName: DataBindRuntimeTestViewModelName.VM3,
    };
}
