// Generated by rive-viewmodel-generator from global_view_models_test.riv.
// Do not edit this file manually.
import {
    RiveBindViewModelInstanceParams,
    RiveGlobalViewModelInstanceParams,
    UntypedRiveViewModel,
} from '@betclicgroup/common/cdk/assets/rive';

export const GlobalViewModelsTestViewModelName = {
    INTERMEDIATE_LIST: 'IntermediateList',
    CHILD: 'Child',
    MAIN: 'Main',
    SIZES: 'Sizes',
    COLORS: 'Colors',
    LABELS: 'Labels',
} as const;

export const IntermediateListInstance = {
    INSTANCE: 'Instance',
    INTERMEDIATE_LIST_INSTANCE: 'IntermediateList Instance',
} as const;
export type IntermediateListInstance = (typeof IntermediateListInstance)[keyof typeof IntermediateListInstance];

export const ChildInstance = {
    CHILD1: 'Child1',
    CHILD3: 'Child3',
    CHILD2: 'Child2',
    CHILD_INSTANCE: 'Child Instance',
} as const;
export type ChildInstance = (typeof ChildInstance)[keyof typeof ChildInstance];

export const MainInstance = {
    INSTANCE: 'Instance',
} as const;
export type MainInstance = (typeof MainInstance)[keyof typeof MainInstance];

export const SizesInstance = {
    INSTANCE: 'Instance',
    SIZES_OVERRIDE: 'Sizes Override',
} as const;
export type SizesInstance = (typeof SizesInstance)[keyof typeof SizesInstance];

export const ColorsInstance = {
    INSTANCE: 'Instance',
    COLORS_OVERRIDE: 'Colors Override',
} as const;
export type ColorsInstance = (typeof ColorsInstance)[keyof typeof ColorsInstance];

export const LabelsInstance = {
    EU: 'EU',
    UK: 'UK',
    US: 'US',
    CH: 'CH',
    LABELS_OVERRIDE: 'Labels Override',
} as const;
export type LabelsInstance = (typeof LabelsInstance)[keyof typeof LabelsInstance];

export interface IntermediateListViewModel {
    setTotalChildren(value: number): void;
}

export interface ChildViewModel {
    setLabel(value: string): void;
}

export interface SizesViewModel {
    setGaps(value: number): void;
}

export interface ColorsViewModel {
    setSecondaryTextColor(value: number): void;
    setSecondaryBackgroundColor(value: number): void;
    setTextColor(value: number): void;
    setBackgroundColor(value: number): void;
}

export interface LabelsViewModel {
    setAlternateCurrency(value: string): void;
    setCurrency(value: string): void;
}

export interface IntermediateListBinding {
    instance?: IntermediateListInstance;
    sizes?: SizesInstance;
    colors?: ColorsInstance;
    labels?: LabelsInstance;
}

export interface ChildBinding {
    instance?: ChildInstance;
    sizes?: SizesInstance;
    colors?: ColorsInstance;
    labels?: LabelsInstance;
}

export interface MainBinding {
    instance?: MainInstance;
    sizes?: SizesInstance;
    colors?: ColorsInstance;
    labels?: LabelsInstance;
}

export function createIntermediateListViewModel(
    viewModel: UntypedRiveViewModel,
    path?: string,
): IntermediateListViewModel {
    return {
        setTotalChildren: value => viewModel.setNumber('totalChildren', value, path),
    };
}

export function createChildViewModel(viewModel: UntypedRiveViewModel, path?: string): ChildViewModel {
    return {
        setLabel: value => viewModel.setString('label', value, path),
    };
}

export function createSizesViewModel(viewModel: UntypedRiveViewModel, path?: string): SizesViewModel {
    return {
        setGaps: value => viewModel.setNumber('gaps', value, path),
    };
}

export function createColorsViewModel(viewModel: UntypedRiveViewModel, path?: string): ColorsViewModel {
    return {
        setSecondaryTextColor: value => viewModel.setColor('secondaryTextColor', value, path),
        setSecondaryBackgroundColor: value => viewModel.setColor('secondaryBackgroundColor', value, path),
        setTextColor: value => viewModel.setColor('textColor', value, path),
        setBackgroundColor: value => viewModel.setColor('backgroundColor', value, path),
    };
}

export function createLabelsViewModel(viewModel: UntypedRiveViewModel, path?: string): LabelsViewModel {
    return {
        setAlternateCurrency: value => viewModel.setString('alternateCurrency', value, path),
        setCurrency: value => viewModel.setString('currency', value, path),
    };
}

export function createIntermediateListBinding(binding: IntermediateListBinding = {}): RiveBindViewModelInstanceParams {
    const globalInstances: RiveGlobalViewModelInstanceParams[] = [];
    if (binding.sizes) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.SIZES,
            instanceName: binding.sizes,
        });
    }
    if (binding.colors) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.COLORS,
            instanceName: binding.colors,
        });
    }
    if (binding.labels) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.LABELS,
            instanceName: binding.labels,
        });
    }

    return {
        viewModelName: GlobalViewModelsTestViewModelName.INTERMEDIATE_LIST,
        instanceName: binding.instance,
        globalInstances,
    };
}

export function createChildBinding(binding: ChildBinding = {}): RiveBindViewModelInstanceParams {
    const globalInstances: RiveGlobalViewModelInstanceParams[] = [];
    if (binding.sizes) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.SIZES,
            instanceName: binding.sizes,
        });
    }
    if (binding.colors) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.COLORS,
            instanceName: binding.colors,
        });
    }
    if (binding.labels) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.LABELS,
            instanceName: binding.labels,
        });
    }

    return {
        viewModelName: GlobalViewModelsTestViewModelName.CHILD,
        instanceName: binding.instance,
        globalInstances,
    };
}

export function createMainBinding(binding: MainBinding = {}): RiveBindViewModelInstanceParams {
    const globalInstances: RiveGlobalViewModelInstanceParams[] = [];
    if (binding.sizes) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.SIZES,
            instanceName: binding.sizes,
        });
    }
    if (binding.colors) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.COLORS,
            instanceName: binding.colors,
        });
    }
    if (binding.labels) {
        globalInstances.push({
            viewModelName: GlobalViewModelsTestViewModelName.LABELS,
            instanceName: binding.labels,
        });
    }

    return {
        viewModelName: GlobalViewModelsTestViewModelName.MAIN,
        instanceName: binding.instance,
        globalInstances,
    };
}
